<?php

namespace app\api\controller;

use app\common\controller\Api;
use app\common\model\Config;

class Ad extends Api
{
    protected $noNeedLogin = ['*'];
    protected $noNeedRight = ['*'];

    private $host_url;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->host_url = config('host_url');
    }

    public function index()
    {
    	$where = [
    	    'is_delete' => 0
        ];
    	if(request()->has('page_count') && request()->param('page_count')) {
    		$page_count = request()->param('page_count');
	    } else {
    	    $page_count = 3;
        }
	    
	    $list = \app\admin\model\Ad::where($where)->field('id,image')->paginate($page_count);
    	return $this->success('ok', $list);
    }
    public function show($id)
    {
        $info = \app\admin\model\Ad::find($id);
        $info['image'] = $this->host_url . $info['image'];
        $info['content'] = preg_replace('/(<img.+src=\"?.+)(\/public)(.+\.(jpg|jpeg|png|gif)\"?.+>)/i',"\${1}{$this->host_url}\${3}",$info['content']);
        return $this->success('ok',$info);
    }
}
