<?php

namespace app\api\controller;

use addons\alisms\library\Alisms;
use app\common\controller\Api;
use app\common\library\Sms as Smslib;
use app\common\model\Config;

class News extends Api
{
    protected $noNeedLogin = ['*'];
    protected $noNeedRight = ['*'];

    private $host_url;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->host_url = config('host_url');
    }

    public function index()
    {
    	$where = ['is_delete' => 0];
	    $list = \app\admin\model\News::where($where)->paginate(10);
	    foreach ($list as &$l) {
	        $l['image'] = $this->host_url . $l['image'];
//	        $l['content'] = preg_replace('/(<img.+src=\"?.+)(\/public)(.+\.(jpg|jpeg|png|gif)\"?.+>)/i',"\${1}{$this->host_url}\${3}",$l['content']);
            $l['content'] = cutstr_html($l['content']);
        }
	    unset($l);
    	return $this->success('ok', $list);
    }
	
	public function show($id)
	{
	    $info = \app\admin\model\News::find($id);
	    $info['image'] = $this->host_url . $info['image'];
	    $info['content'] = preg_replace('/(<img.+src=\"?.+)(\/public)(.+\.(jpg|jpeg|png|gif)\"?.+>)/i',"\${1}{$this->host_url}\${3}",$info['content']);
		return $this->success('ok',$info);
    }

}
